travis:
  secure:
    BINSTAR_TOKEN: CEvbu7zwXnB66j6SJekFHVefcwXebFCePSisARy78PG2knyQmWJwwTnSflej/oectqVZVFeTixsKMSUBS4yWFgTUZLz5NwaGPUtXYA5+bnDh5R+0HNXwmaHL963zFxQD9Wg0JFxlydypGvta3ZKbvmVV4ZNk5Nfl7cXWODyqPgqT+li4sTJJmYhzMBbaq9blahvBWMqFqw07X9dQv5tGwXg3sIPsJSpjqKUA2MWnFi7BDCkXPeRQpl7EOI4kNPWEzkXSEWrey/DZ6VOvX2k4j0JSsn4T9vrZ1W/gyT2W1Cdg73/EeSrgqfgYP6FLINYFTQJPH2yU4OzZCE8XLxgZSfrL2FNuHQbI1VjuXpFAP9iisRwAVJEsSzBrzZCnfL+RTGkPIqpdqzyWwXP/1WKw0Brb6HQtdUFyusvktkpjzGt21z0ULz/EAkFU1KXiug58ym7NFif2z2NjuwI03beLLX1AAVM1MhkKA6PR+6rRNUrPmfljXVRJLYkTZEC5bA0AQ9I+VaHrrROHIA4rcPY9O/32ptwujdsUxKJLgTOtJXmpcSgz9lH43PeVv8R6kE06LEdInJrO100PhBmTlz6txEhbkPEnlN1HT5mZUF/2A6Pwvhs2jdgWebELSa9M5VdWy673s0NgmSFe4i7fDX1c58B8gV5LXCPlZ7Ve4mOOLm0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
